"""'upgrade'

Revision ID: 0283f81f69a0
Revises: 01bbfcd828c9
Create Date: 2023-06-05 16:31:58.687728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0283f81f69a0'
down_revision = '01bbfcd828c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'percentage')
    # ### end Alembic commands ###
